# Generated by Django 4.0.4 on 2022-05-30 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identificador de la categoría')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nobre de la categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('codComuna', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Código de la comuna')),
                ('nomComuna', models.CharField(max_length=100, verbose_name='Nombre de la comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('codRegion', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Código de la región')),
                ('nomRegion', models.CharField(max_length=100, verbose_name='Nombre de la región')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Patente del vehículo (*)')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca del vehículo')),
                ('modelo', models.CharField(max_length=20, null=True, verbose_name='Modelo del vehículo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('idContacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres (*))')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos (*)')),
                ('celular', models.IntegerField(verbose_name='Celular (*)')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo electrónico (*)')),
                ('direccion', models.CharField(max_length=250, verbose_name='Dirección (*)')),
                ('codComuna', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.comuna')),
                ('codRegion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.region')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='codRegion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
    ]
