# Generated by Django 4.0.4 on 2022-06-05 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('codComuna', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Código de la comuna')),
                ('nomComuna', models.CharField(max_length=100, verbose_name='Nombre de la comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('codRegion', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Código de la región')),
                ('nomRegion', models.CharField(max_length=100, verbose_name='Nombre de la región')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('idContacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres (*)')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos (*)')),
                ('celular', models.IntegerField(verbose_name='Celular (*)')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo electrónico (*)')),
                ('direccion', models.CharField(max_length=250, verbose_name='Dirección (*)')),
                ('codComuna', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.comuna', verbose_name='Comuna (*)')),
                ('codRegion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.region', verbose_name='Región (*)')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='codRegion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
    ]
