# Generated by Django 4.0.4 on 2022-06-01 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='codComuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.comuna', verbose_name='Comuna (*)'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='codRegion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.region', verbose_name='Región (*)'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombres',
            field=models.CharField(max_length=100, verbose_name='Nombres (*)'),
        ),
    ]
