# Generated by Django 4.0.4 on 2022-06-05 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código de la categoría')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoría')),
            ],
        ),
        migrations.AlterField(
            model_name='contacto',
            name='idContacto',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador del contacto'),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador del producto')),
                ('nombreCorto', models.CharField(max_length=100, verbose_name='Nombre corto del producto')),
                ('nombreLargo', models.CharField(max_length=200, verbose_name='Nombre largo del producto')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripción del producto')),
                ('precio', models.IntegerField(verbose_name='Precio del producto')),
                ('imagen', models.CharField(max_length=100, verbose_name='Imagen del producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.categoria')),
            ],
        ),
    ]
