# Generated by Django 4.0.4 on 2022-06-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_fundacion_alter_contacto_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundacion',
            name='descripcion',
            field=models.TextField(max_length=1000, verbose_name='Descripción de la fundación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=1000, verbose_name='Descripción del producto'),
        ),
    ]
