# Generated by Django 4.0.4 on 2022-06-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_alter_contacto_idcontacto_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='celular',
            field=models.PositiveIntegerField(verbose_name='Celular (*)'),
        ),
    ]
