# Generated by Django 3.1 on 2022-06-13 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contacto_codcomuna_alter_contacto_codregion_and_more'),
        ('core', '0003_alter_contacto_celular'),
    ]

    operations = [
    ]
