# Generated by Django 3.1 on 2022-06-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20220613_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundacion',
            fields=[
                ('idFundacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador de la fundación')),
                ('nombreCorto', models.CharField(max_length=100, verbose_name='Nombre corto de la fundación')),
                ('nombreLargo', models.CharField(max_length=200, verbose_name='Nombre largo de la fundación')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripción de la fundación')),
                ('sitioWeb', models.URLField(null=True, verbose_name='Sitio web de la fundación')),
                ('imagen', models.ImageField(null=True, upload_to='fundaciones')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
