# Generated by Django 4.0.4 on 2022-06-14 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_fundacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.categoria', verbose_name='Categoria del producto (*)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=1000, verbose_name='Descripción del producto (*)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador del producto (*)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen del producto (*)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombreCorto',
            field=models.CharField(max_length=100, verbose_name='Nombre corto del producto (*)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombreLargo',
            field=models.CharField(max_length=200, verbose_name='Nombre largo del producto (*)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(verbose_name='Precio del producto (*)'),
        ),
    ]
