# Generated by Django 4.0.4 on 2022-06-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_producto_categoria_alter_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fundaciones', verbose_name='Imagen de la fundación'),
        ),
        migrations.AlterField(
            model_name='fundacion',
            name='sitioWeb',
            field=models.CharField(max_length=200, null=True, verbose_name='Sitio web de la fundación'),
        ),
    ]
