# Generated by Django 3.1 on 2022-11-04 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_fundacion_imagen_alter_fundacion_sitioweb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='codRegion',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='codComuna',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='codRegion',
        ),
        migrations.DeleteModel(
            name='Fundacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
