# Generated by Django 3.1 on 2022-11-04 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_parametro_producto_pyme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parametro',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Pyme',
        ),
    ]
