# Generated by Django 3.1 on 2022-11-04 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_parametro_producto_pyme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código de la categoría')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('codComuna', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Código de la comuna')),
                ('nomComuna', models.CharField(max_length=100, verbose_name='Nombre de la comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('idContacto', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador del contacto')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres (*)')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos (*)')),
                ('celular', models.PositiveIntegerField(verbose_name='Celular (*)')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo electrónico (*)')),
                ('direccion', models.CharField(max_length=250, verbose_name='Dirección (*)')),
                ('codComuna', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.comuna', verbose_name='Comuna (*)')),
            ],
        ),
        migrations.CreateModel(
            name='Fundacion',
            fields=[
                ('idFundacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador de la fundación')),
                ('nombreCorto', models.CharField(max_length=100, verbose_name='Nombre corto de la fundación')),
                ('nombreLargo', models.CharField(max_length=200, verbose_name='Nombre largo de la fundación')),
                ('descripcion', models.TextField(max_length=1000, verbose_name='Descripción de la fundación')),
                ('sitioWeb', models.CharField(max_length=200, null=True, verbose_name='Sitio web de la fundación')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fundaciones', verbose_name='Imagen de la fundación')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('codRegion', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Código de la región')),
                ('nomRegion', models.CharField(max_length=100, verbose_name='Nombre de la región')),
            ],
        ),
        migrations.DeleteModel(
            name='Parametro',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='pyme',
        ),
        migrations.DeleteModel(
            name='Pyme',
        ),
        migrations.AddField(
            model_name='contacto',
            name='codRegion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.region', verbose_name='Región (*)'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='codRegion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.categoria', verbose_name='Categoria del producto (*)'),
            preserve_default=False,
        ),
    ]
