# Generated by Django 3.1 on 2022-11-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fundacion',
            fields=[
                ('idFundacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador de la fundación')),
                ('nombreCorto', models.CharField(max_length=100, verbose_name='Nombre corto de la fundación')),
                ('nombreLargo', models.CharField(max_length=200, verbose_name='Nombre largo de la fundación')),
                ('descripcion', models.TextField(max_length=1000, verbose_name='Descripción de la fundación')),
                ('sitioWeb', models.CharField(max_length=200, null=True, verbose_name='Sitio web de la fundación')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fundaciones', verbose_name='Imagen de la fundación')),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('codParametro', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código del parámetro')),
                ('nombreParametro', models.CharField(max_length=50, verbose_name='Nombre del parámetro')),
                ('valor', models.CharField(max_length=10, verbose_name='Valor del parámetro')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador del producto (*)')),
                ('nombreCorto', models.CharField(max_length=100, verbose_name='Nombre corto del producto (*)')),
                ('nombreLargo', models.CharField(max_length=200, verbose_name='Nombre largo del producto (*)')),
                ('descripcion', models.TextField(max_length=1000, verbose_name='Descripción del producto (*)')),
                ('precio', models.IntegerField(verbose_name='Precio del producto (*)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen del producto (*)')),
            ],
        ),
    ]
