# Generated by Django 3.1 on 2022-11-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pyme',
            fields=[
                ('idPyme', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador de la PYME')),
                ('nombreCorto', models.CharField(max_length=100, verbose_name='Nombre corto de la PYME')),
                ('nombreLargo', models.CharField(max_length=200, verbose_name='Nombre largo de la PYME')),
                ('descripcion', models.TextField(max_length=1000, verbose_name='Descripción de la PYME')),
                ('sitioWeb', models.CharField(max_length=200, null=True, verbose_name='Sitio web de la PYME')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='pymes', verbose_name='Imagen de la PYME')),
            ],
        ),
        migrations.DeleteModel(
            name='Fundacion',
        ),
    ]
