# Generated by Django 3.1 on 2022-11-05 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_auto_20221105_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='pyme',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='api_rest.pyme', verbose_name='PYME que vende el producto (*)'),
            preserve_default=False,
        ),
    ]
